#+title: 飞单训练
#+startup: content
#+author: Gaeric
#+HTML_HEAD: <link href="./worg.css" rel="stylesheet" type="text/css">
#+HTML_HEAD: <link href="/static/css/worg.css" rel="stylesheet" type="text/css">
#+OPTIONS: ^:{}
* 简介
  声笔飞单方案需要进行单字练习才能进步，这部分练习要花费大量的时间，它也理应进入每天进步两个一点点的记录之中。

  在当前，练习是两个一点点的主要内容之一；在练字熟练之后，它仍然是完成上述每天进步两个一点点的保底项目。

  而个人博客，是记录这个练习的理想位置！
* Plan
** 第一期计划
   练过常用单字前500，十字一组，击键过六

   练过105个声笔字，十字一组，击键过六

   每天记录明天需要完成的单字，以便于在其它地方练习
*** 声笔字
    如同孔明自快话开口正
    道无怕经二双公民来前
    线年内安然回南国若说
    阿维当农夫片上方家暗
    笑她进得高中好体面心
    想事成且大为别看晚儿
    那小子强力对手头也破
    从此把着全日用除非白
    天会给还部分次品立飞
    过让利几起眼皮部名门
    里外有意见
*** 前五百
    的一是了不在有个人这
    上中大为来我到出要以
    时和地们得可下对生也
    子就过能他会多发说而
    于自之用年行家方后作
    成开面事好小心前所道
    法如进着同经分定都然
    与本还其当起动已两点
    从问里主实天高去现长
    此三将无国全文理明日
    些看只公等十意正外想
    间把情者没重相那向知
    因样学应又手但信关使
    种见力名二处门并口么
    先位头回话很再由身入
    内第平被给次别几月真
    立新通少机打水果最部
    何安接报声才体今合性
    西你放表目加常做己老
    四件解路更走比总金管
    光工结提任东原便美及
    教难世至气神山数利书
    代直色场变记张必受交
    非服化求风度太万各算
    边王什快许连五活思该
    步海指物则女或完马强
    言条特命感清带认保望
    转传儿制干计民白住字
    它义车像反象题却流且
    即深近形取往系量论告
    息让决未花收满每华业
    南觉电空眼听远师元请
    容她军士百办语期北林
    识半夫客战院城候单音
    令改功程爱德复切随李
    员离轻观青足落叫根怎
    持精送众影八首包准兴
    红达早尽故房引火站似
    找备调断设格消拉照布
    友整术石展紧据终周式
    举飞片虽易运笑云建谈
    界务写钱商乐推注越千
    微若约英集示呢待坐议
    乎留称品志黑存六造低
    江念产刻节尔吃势依图
    共曾响底装具喜严九况
    跟罗须显热病证刚治绝
    群市死阳确究久除答段
    台视领失司亲始极双闻
    官政类黄武七支费父统
*** 中五百
    查般斯倒突号树拿克初
    广奇愿欢希母香破谁致
    线急古既句京甚仍晚争
    游龙余护另器细木权星
    哪苦孩试朝阿队居害独
    讲错局男差参社换选止
    际假汉够诉资密案史较
    环投静宝专修室区料帮
    衣竟模脸善兵考规联团
    冷玉施派纪采历顾春责
    夜画惊银负续吗简章左
    块索酒值态按陈河巴冲
    阵境助角户乱呼灵脚继
    楼景怕停铁异谢否伤兰
    置医良承福科属围需退
    基右速适药怀击买素背
    岁土忙充排价质遇端列
    印贵疑露哥杀标招血礼
    弟亮齐穿脑委州某顺省
    讨尚维板散项状追笔副
    层沙养读习永草胡济执
    察归富座雨堂威忽苏船
** 第二期计划
   1. 每天温习一次前五百
   2. 每天重复练习两三百字的短文，或完成一篇赛文
** 第三期计划
   1. 开发慢字收集功能，并将慢字收集中的字记录下来
   2. 针对慢字，进行专项练习，练习方式为多字一组，按前五百的方式来练
*** record
    魔魅游丝艇
    临户奶辉浴
*** 声笔笔
    截瞬滋隐幼骤愉肌筑洪
    苍舒陷晰订印茸蜜掏俊
    懒掏挣誓添隐纱喘鞋奏
    屠岩膊玲浅阁潇邀朗鲁
    含砸抑
** 第四期计划
   不再特意练习某个单字，而是开始大量跟打，并开发错字收集功能，将错字收集起来

   查般斯倒突号树拿克初
   广奇愿欢希母香破谁致
   线急古既句京甚仍晚争
   游龙余护另器细木权星
   哪苦孩试朝阿队居害独
   讲错局男差参社换选止
   际假汉够诉资密案史较
   环投静宝专修室区料帮
   衣竟模脸善兵考规联团
   冷玉施派纪采历顾春责
** 第五期计划
   至从前五百练习完成之后，后续的练习计划一直没有得到良好的执行，我反思第四期计划的执行状况，前期大量打字，但是没有对单字进行练习，这样练习效率过低，很快被我放弃；

   效率高的练习方式就是按顺序练习单字，但是在一段时间之后这个练习很快就中止了；为什么会被中止呢？

   首先，有段时间出现了手指疼的身体状况，这直接打断了我的练习进度；

   后来手指虽然恢复，但是每天练习需要消耗一个小时时间，且其中总是重复性的内容，让我难以开始。

   于是我定下了各有挑战性的第五期做法：在脚本中计算自己的击键速度，对中五百字设定一个速度基准，十字一组练习，过这个基准就到下一组

   第五期计划的脚本已经调整完成，整理后会再次规范在这里。
* Note
** review
*** 中五百完成进度
    已完成了中五百全字练习，十字一组组均击键过3，接下来进入挑战模式，第一个星期完成十字一组击键过四，第二个星期完成十字一组击键过五

    已完成中五百全字过4

*** 难度和效率是需要平衡的两个关键点
*** 需要有合理的方法解决错字问题
    当前正常使用时，错字问题突出，相比正常跟打情况下，错字增加，需要改进

    正常跟打文章，每一次错误时将错字记录下来，然后将错字按错误排成文章，进行跟打练习。
*** 多练习是最好的进步方式
    这些天居家，在一个简单的跟打器上打字练习，练习方式类似于盲打，感觉自己进步的很快。

    进步的方面主要有两点，一是终于对aeiou的笔画拆分有了一定的反射，二是因为完全盲打，记住了很多字的拆法，越来越有规律，节奏也越来越好
*** 慢错字收集
    吻滑弄迷缠嫩剥诗育胸
    独佳痛舌缠舌逊呦热摆
    婉媚态泡沫烈飞粗奸蛮
    躏痒哟迷躯棒龟厮磨阴
    核停龟噗哧织奏君犯抽
    未育胸蛮横熟扯育稚刑
    容纳依诗稚仿丝锻瑕狂
    凌幼滑肤紧牙猛舔虐紫
    咬野惩棒呻骄勾随送骤
    痛扎诗粗凶猛挛热突阴
    君抓幼喷滴液君棒沾浆
    杂缝娜皇争城占噩君司
    雅收且晶判占九判权晶
    座解君却露羞垂绯靡论
    限旁薄露线胸革房靴狂
    贱皇魔护持剑刃锋卫护
    寒论剑合融息锋漆镶璨
    夺石凡袭矛辉煌利芒另
    鞭削撕烈啸狡滑铁如泥
    舞凌九
*** 第二期计划未执行
    回过头来，练习完成前五百之后，我就没有进一步练习了，针对这个问题，需要专门分析一下，并进行改进

    今天突然发现，打字连续不中断带来的正反馈给人非常强的激励，也许可以从这个地方入手去解决这个问题
    [2022-01-25 Tue]
*** 练习review2
    前面的计划执行了几天，发现了一些问题

    1. 因为每天只打两组字，其它单字得不到练习

    2. 没有击键压力，随着单字遍数的增加，进步的速度放缓

    取消了乱序练习，每天晚上的练习恢复

    因为上述变化，取消待突破项目

    
    每天练习二十个生字，每个字单练50个，以保证单字的编码熟练；然后十字一组，十组一次，练习五次；
    然后在跟打器上，至第一个字开始，十字一组击键过六
*** 练习review1
    练习的阻力越来越大了，我的方法可能出了很严重的问题，让现在的状态不可持续

    为什么会这样呢？
    1. 对今天即将练习的内容毫无了解，预期会花费大量的时间，而且对心智有很高的负担
    2. 前一天的练习只是刚好过了击键，并不意味着已经熟练，在当天的练习中，还需要花费大量的精力去重练
    3. 晚上已经昏沉，只想休息

    综上，练字成为了一个负担性的工作！

    让我们来重新看看这个过程：练字击键过六，实际上是形成条件反射的过程；而条反的形成，实际依赖的是大量的练习；
    大量练习需要花费很长时间，这和短时间要求击键是相矛盾的；

    那我应该考虑长期练习，集中突破的方式，于是试验性的将计划变更如下：

    1. 将练习时间调整为早上

    2. 每天练习二十个生字，每个字单练50个，以保证单字的编码熟练；然后十字一组，十组一次，练习十次；再然后十字乱序，练习50次；每天总练习量为4000字！

    3. 完成了练习需要的脚本，新增待突破项
** training_script
   #+begin_src python
     import random
     import json


     RECORD_FILE = 'record.json'
     SINGLE_TIMES = 2
     REPEAT_TIMES = 2
     RANDOM_TIMES = 2


     class Record:
         def __init__(self, json_file):
             try:
                 with open(json_file, encoding='utf-8') as fp:
                     content = json.load(fp)
                 self.characters = content['characters']
                 self.single_times = content['single']['times']
                 self.single_chara = content['single']['chara']
                 self.single_state = content['single']['state']
                 self.repeat_times = content['repeat_times']
                 self.random_times = content['random_times']
                 self.record_speed = content['record_speed']
                 self.record_typed = content['record_typed']
             except (FileNotFoundError, AttributeError):
                 self.clear_record()
                 self.record()

         def __str__(self):
             return f'characters: {self.characters}\n\
     single_chara: {self.single_chara}\n\
     single_times: {self.single_times}\n\
     single_state: {self.single_state}\n\
     repeat_times: {self.repeat_times}\n\
     random_times: {self.random_times}\n\
     record_speed: {self.record_speed}\n\
     record_typed: {self.record_typed}\n\
     '

         def clear_record(self):
             self.characters = ''
             self.single_chara = ''
             self.single_times = 0
             self.single_state = ''
             self.repeat_times = 0
             self.random_times = 0
             self.record_speed = 0
             self.record_typed = 0

         def record(self):
             content = {}
             content['characters'] = self.characters
             content['single'] = {
                 'chara': self.single_chara,
                 'times': self.single_times,
                 'state': self.single_state
             }
             content['repeat_times'] = self.repeat_times
             content['random_times'] = self.random_times
             content['record_speed'] = self.record_speed
             content['record_typed'] = self.record_typed
             with open(RECORD_FILE, 'w', encoding='utf-8') as fp:
                 json.dump(content, fp, indent=4, ensure_ascii=False)


         def practice(self, prompt, times):
             while True:
                 input_str = input(f'{prompt}|{times:03}|: ')
                 if input_str == prompt:
                     break

         def do_single(self):
             while self.single_state != 'done':
                 if self.single_chara == '':
                     self.single_chara = self.characters[0]
                     self.single_times = 0
                 if self.single_times == SINGLE_TIMES:
                     if self.characters.index(
                             self.single_chara) == len(self.characters) - 1:
                         self.single_chara = ''
                         self.single_times = 0
                         self.single_state = 'done'
                         self.record()
                         break


                     self.single_chara = list(self.characters[
                         self.characters.index(self.single_chara) + 1])
                     self.single_times = 0

                     prompt = ''.join([self.single_chara for i in range(10)])
                     times = self.single_times + 1
                     self.practice(prompt, times)
                     self.single_times += 1
                     self.record()

         def do_random(self):
             while self.random_times < RANDOM_TIMES:
                 group = list(self.characters)
                 random.shuffle(group)
                 self.practice(''.join(group), self.random_times + 1)
                 self.random_times += 1
                 self.record()

         def do_repeat(self):
             while self.repeat_times < REPEAT_TIMES:
                 self.practice(self.characters, self.repeat_times + 1)
                 self.repeat_times += 1
                 self.record()

         def training(self):
             self.do_single()
             self.do_repeat()
             self.do_random()
   #+end_src
   [2022-01-04 Tue]
